# MAIN base
baseURL = "https://liamgreen.info/"
languageCode = "en-us"
title = "Liam Green Info"
theme = "apsho"
enableRobotsTXT = true

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Services"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Testimonials"
    url = "#testimonial"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Services"
    url = "#services"
    weight = 2
[[menu.sitemap]]
    name = "Testimonials"
    url = "#testimonial"
    weight = 3
[[menu.sitemap]]
    name = "About Me"
    url = "#faq"
    weight = 4    
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 5

# Footer Address
[params.address]
address = "Christchurch, New Zealand"
email = "liamgreenit@gmail.com"
phone = "+(64) 0220726067"

# Footer Social
[params.social]
linkedin = "https://www.linkedin.com/in/liam-green-nz"
github = "https://github.com/liamsgreen"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Let's get Started"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://liamgreen.info/\" target=\"_blank\">Liam Green </a> {year}"

#contact
email = "liamgreenit@gmail.com"
